import '@/root/globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { Providers } from '../root/providers'
import { NavBar } from './components/nav-bar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Главная',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru' suppressHydrationWarning>
			<body className={`${inter.className}`}>
				<Providers>
					<div className='flex min-h-screen flex-col justify-between gap-[20px] sm:gap-[40px]'>
						<div className='flex-shrink-0'>
							<NavBar />
						</div>
						<main className='container flex-grow'>{children}</main>
						<footer>dsadas</footer>
					</div>
				</Providers>
			</body>
		</html>
	)
}
